"""Run metadata model — ``run_metadata.json`` schema and per-file validation.

``run_metadata.json`` is generated by the submission CLI for every measurement
point and lives at ``pareto/<system>/<model>/results/point_<N>/run_metadata.json``.

Validation policy:
    * Every measurement field must be present **and non-null**.
    * ``config_summary`` is either a string of length >= 4 or a structured
      :class:`ConfigSummary` object.
    * Only ``config_summary_notes``, ``link_config``, and ``link_logs`` may be
      null — but their keys must still be present.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, StringConstraints

__all__ = ["ConfigSummary", "RunMetadata"]


class ConfigSummary(BaseModel):
    """Structured parallelism/config summary (the object form of ``config_summary``)."""

    model_config = ConfigDict(extra="allow")

    disaggregated: bool | None = None
    expert_parallel: int | None = None
    tensor_parallel: int | None = None
    pipeline_parallel: int | None = None
    data_parallel: int | None = None
    batch: int | None = None


# config_summary accepts either a structured object or a free-form string (len >= 4).
_ConfigSummaryStr = Annotated[str, StringConstraints(min_length=4)]


class RunMetadata(BaseModel):
    """Parsed contents of ``run_metadata.json``.

    All fields are required and non-null except ``config_summary_notes``,
    ``link_config``, and ``link_logs``, whose keys must be present but whose
    values may be null.
    """

    model_config = ConfigDict(extra="allow")

    # Identity / configuration
    run_date: str
    node_config: str
    config_summary: ConfigSummary | _ConfigSummaryStr
    config_summary_notes: str | None
    concurrency: int

    # Headline metrics
    system_tps: float
    tps_per_user: float
    ttft: float
    qps: float
    tps_utilization: float

    # Run accounting
    measured_total_output_tokens: int
    measured_run_duration: float
    measured_total_requests: int

    # Optional reference links (key required, value may be null)
    link_config: str | None
    link_logs: str | None

    # TTFT latencies
    measured_latency_ttft_min: float
    measured_latency_ttft_average: float
    measured_latency_ttft_p50: float
    measured_latency_ttft_p90: float
    measured_latency_ttft_p95: float
    measured_latency_ttft_p99: float
    measured_latency_ttft_p999: float
    measured_latency_ttft_max: float

    # TPOT latencies
    measured_latency_tpot_min: float
    measured_latency_tpot_average: float
    measured_latency_tpot_p50: float
    measured_latency_tpot_p90: float
    measured_latency_tpot_p95: float
    measured_latency_tpot_p99: float
    measured_latency_tpot_p999: float
    measured_latency_tpot_max: float

    # End-to-end request latencies
    measured_latency_request_min: float
    measured_latency_request_average: float
    measured_latency_request_p50: float
    measured_latency_request_p90: float
    measured_latency_request_p95: float
    measured_latency_request_p99: float
    measured_latency_request_p999: float
    measured_latency_request_max: float
