# SPDX-FileCopyrightText: Copyright (c) 2024 MLCommons
# SPDX-License-Identifier: Apache-2.0
"""Parse a local run folder into a RunCreate API payload.

Run folder layout:

    <run_folder>/
        system_desc.json              — org/system/model/dataset metadata (flat format)  [required]
        config.yaml                   — benchmark configuration                           [required]
        result_summary.json           — raw benchmark metrics                             [required]
        run_metadata.json             — run-level metadata
        results.json                  — high-level result summary
        events.jsonl                  — per-event log
        report.txt                    — human-readable report
        sample_idx_map.json           — sample index mapping
        metrics/final_snapshot.json   — metrics snapshot
        serving_config.json           — serving configuration (auto-generated, optional)
        mlperf-system-info-*.json     — hardware snapshot (auto-generated by sysinfo tool, optional)
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, cast

import yaml

from ..exceptions import RunFolderError
from ..truncation import truncate_responses

__all__ = ["parse_run_folder", "build_archive"]

_REQUIRED_FILES = ("system_desc.json", "config.yaml", "result_summary.json")


def parse_run_folder(path: Path) -> dict[str, Any]:
    """Parse *path* and return a dict suitable for ``POST /runs``.

    Args:
        path: Directory containing ``system_desc.json``, ``config.yaml``,
              and ``result_summary.json``.

    Returns:
        Dict with keys matching ``RunCreate`` schema fields.

    Raises:
        RunFolderError: If any required file is absent or malformed.
    """
    path = path.resolve()
    if not path.is_dir():
        raise RunFolderError(f"Run folder does not exist or is not a directory: {path}")

    _validate_required_files(path)

    system_info = _load_json(path / "system_desc.json")
    config = _load_yaml(path / "config.yaml")
    result_summary = _load_json(path / "result_summary.json")

    started_at, finished_at = _extract_timestamps(result_summary)
    benchmark_version = result_summary.get("git_sha") or "unknown"

    return {
        "benchmark_version": benchmark_version,
        "started_at": started_at.isoformat(),
        "finished_at": finished_at.isoformat(),
        "system_info": system_info,
        "config": config,
        "result_summary": result_summary,
    }


def _validate_required_files(path: Path) -> None:
    missing = [f for f in _REQUIRED_FILES if not (path / f).exists()]
    if missing:
        raise RunFolderError(f"Run folder {path} is missing required file(s): {', '.join(missing)}")


def _load_json(file_path: Path) -> dict[str, Any]:
    try:
        return cast(dict[str, Any], json.loads(file_path.read_text(encoding="utf-8")))
    except json.JSONDecodeError as exc:
        raise RunFolderError(f"Invalid JSON in {file_path.name}: {exc}") from exc


def _load_yaml(file_path: Path) -> dict[str, Any]:
    try:
        data = yaml.safe_load(file_path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise RunFolderError(
                f"{file_path.name} must be a YAML mapping, got {type(data).__name__}"
            )
        return data
    except yaml.YAMLError as exc:
        raise RunFolderError(f"Invalid YAML in {file_path.name}: {exc}") from exc


def _coerce_epoch(value: Any) -> datetime | None:
    """Interpret *value* as a Unix epoch timestamp, returning an aware UTC datetime.

    The unit (seconds, milliseconds, microseconds, or nanoseconds) is inferred by
    picking the scale whose resulting calendar year is plausible (2020–2100). Returns
    None for non-numeric, non-positive, or out-of-range values.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)) or value <= 0:
        return None
    for scale in (1, 1e3, 1e6, 1e9):  # seconds, ms, µs, ns
        try:
            dt = datetime.fromtimestamp(value / scale, tz=timezone.utc)
        except (OverflowError, OSError, ValueError):
            continue
        if 2020 <= dt.year <= 2100:
            return dt
    return None


def _extract_timestamps(result_summary: dict[str, Any]) -> tuple[datetime, datetime]:
    """Derive started_at and finished_at from result_summary.

    Prefers the benchmark's wall-clock ``test_started_at`` when present and sane;
    otherwise falls back to current time minus duration.
    """
    duration_s: float = result_summary.get("duration_ns", 0) / 1e9

    started_at = _coerce_epoch(result_summary.get("test_started_at"))
    if started_at is not None:
        return started_at, started_at + timedelta(seconds=duration_s)

    finished_at = datetime.now(tz=timezone.utc)
    started_at = finished_at - timedelta(seconds=duration_s)
    return started_at, finished_at


def _started_at_to_run_date(started_at: str) -> str | None:
    """Convert an ISO 8601 ``started_at`` datetime to a ``YYYY-MM-DD`` date string.

    Returns None if the value cannot be parsed. Handles a trailing ``Z`` (UTC),
    which ``datetime.fromisoformat`` does not accept before Python 3.11.
    """
    value = started_at.strip()
    if value.endswith(("Z", "z")):
        value = value[:-1] + "+00:00"
    try:
        return datetime.fromisoformat(value).date().isoformat()
    except ValueError:
        return None


def build_archive(folder: Path, dest: Path | None = None, run_date: str | None = None) -> Path:
    """Create a .tar.gz archive of *folder*.

    Args:
        folder: Directory to archive.
        dest: Destination file path. Defaults to ``<folder.name>.tar.gz`` beside *folder*.
        run_date: When provided and the folder contains a ``run_metadata.json``, the
            archived copy of that file has its ``run_date`` field set to this value.
            The source folder on disk is left untouched.

    The archived copy of every ``results.json`` (top-level and any nested one,
    e.g. ``accuracy/results.json``) has its verbose ``responses`` list truncated
    (see :func:`truncate_responses`) to keep uploads small; the source folder on
    disk is never mutated.

    Returns:
        Path of the created archive.
    """
    import io
    import tarfile

    if dest is None:
        dest = folder.parent / f"{folder.name}.tar.gz"

    # In-memory replacements for specific archive members, keyed by arcname. The
    # matching files on disk are excluded from the tar and these copies appended,
    # so the source folder is never mutated.
    replacements: dict[str, bytes] = {}

    meta_path = folder / "run_metadata.json"
    if run_date is not None and meta_path.is_file():
        try:
            metadata = json.loads(meta_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            metadata = None
        if isinstance(metadata, dict):
            metadata["run_date"] = run_date
            replacements[f"{folder.name}/run_metadata.json"] = json.dumps(
                metadata, indent=2
            ).encode("utf-8")

    for results_path in sorted(folder.rglob("results.json")):
        if not results_path.is_file():
            continue
        original = results_path.read_bytes()
        truncated = truncate_responses(original)
        if truncated != original:
            rel = results_path.relative_to(folder).as_posix()
            replacements[f"{folder.name}/{rel}"] = truncated

    with tarfile.open(dest, "w:gz") as tar:
        if not replacements:
            tar.add(folder, arcname=folder.name)
        else:
            tar.add(
                folder,
                arcname=folder.name,
                filter=lambda ti: None if ti.name in replacements else ti,
            )
            for arcname, data in replacements.items():
                info = tarfile.TarInfo(name=arcname)
                info.size = len(data)
                tar.addfile(info, io.BytesIO(data))
    return dest
